---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 拯救兔.
--- DateTime: 2025/12/22 19:24
---
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 释放锁
    return redis.call('del', KEYS[1])
end
return 0